<a href="https://colab.research.google.com/github/gawankarsanket/dswithchirag_assignments/blob/main/EDA_Assignment_Healthexp_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Libraries

In [1]:
import pandas as pd

### Reading CSV file into dataframe

In [2]:
df=pd.read_csv("/content/healthexp.csv")

In [3]:
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [4]:
#Total Cells rowsxcolumn
df.size

1096

In [5]:
#number of rows and columns
df.shape

(274, 4)

In [6]:
df.dtypes

Year                 int64
Country             object
Spending_USD       float64
Life_Expectancy    float64
dtype: object

In [7]:
df.columns

Index(['Year', 'Country', 'Spending_USD', 'Life_Expectancy'], dtype='object')

In [8]:
df.values

array([[1970, 'Germany', 252.311, 70.6],
       [1970, 'France', 192.143, 72.2],
       [1970, 'Great Britain', 123.993, 71.9],
       ...,
       [2020, 'Great Britain', 5018.7, 80.4],
       [2020, 'Japan', 4665.641, 84.7],
       [2020, 'USA', 11859.179, 77.0]], dtype=object)

In [9]:
df.describe()

              Year  Spending_USD  Life_Expectancy
count   274.000000    274.000000       274.000000
mean   1996.992701   2789.338905        77.909489
std      14.180933   2194.939785         3.276263
min    1970.000000    123.993000        70.600000
25%    1985.250000   1038.357000        75.525000
50%    1998.000000   2295.578000        78.100000
75%    2009.000000   4055.610000        80.575000
max    2020.000000  11859.179000        84.700000

In [10]:
df['Country'].unique()

array(['Germany', 'France', 'Great Britain', 'Japan', 'USA', 'Canada'],
      dtype=object)

In [11]:
df[["Country","Spending_USD"]]

           Country  Spending_USD
0          Germany       252.311
1           France       192.143
2    Great Britain       123.993
3            Japan       150.437
4              USA       326.961
..             ...           ...
269        Germany      6938.983
270         France      5468.418
271  Great Britain      5018.700
272          Japan      4665.641
273            USA     11859.179

[274 rows x 2 columns]

In [12]:
df_country=df.groupby("Country")

In [15]:
df_country[['Spending_USD']].mean()

               Spending_USD
Country
Canada          2685.778341
France          3045.145057
Germany         2667.280200
Great Britain   2034.192465
Japan           1860.257902
USA             4388.570529

##Year wise life expetency trend

In [20]:

df.groupby('Year')[['Life_Expectancy']].mean()

      Life_Expectancy
Year
1970        71.520000
1971        71.920000
1972        71.800000
1973        72.033333
1974        72.400000
1975        72.850000
1976        73.325000
1977        73.700000
1978        73.866667
1979        74.500000
1980        74.233333
1981        74.620000
1982        74.920000
1983        75.120000
1984        75.420000
1985        75.616667
1986        75.860000
1987        76.180000
1988        76.260000
1989        76.480000
1990        76.916667
1991        77.060000
1992        77.100000
1993        77.083333
1994        77.450000
1995        77.450000
1996        77.766667
1997        78.066667
1998        78.283333
1999        78.383333
2000        78.716667
2001        78.950000
2002        79.083333
2003        79.133333
2004        79.683333
2005        79.766667
2006        80.150000
2007        80.366667
2008        80.483333
2009        80.766667
2010        80.933333
2011        81.100000
2012        81.216667
2013        81.316667
2014        81.633333
2015        81.433333
2016        81.616667
2017        81.633333
2018        81.683333
2019        81.833333
2020        81.200000

In [23]:
df.groupby("Year")[['Year','Life_Expectancy']].describe()

      Year                                                       \
     count    mean  std     min     25%     50%     75%     max
Year
1970   5.0  1970.0  0.0  1970.0  1970.0  1970.0  1970.0  1970.0
1971   5.0  1971.0  0.0  1971.0  1971.0  1971.0  1971.0  1971.0
1972   3.0  1972.0  0.0  1972.0  1972.0  1972.0  1972.0  1972.0
1973   3.0  1973.0  0.0  1973.0  1973.0  1973.0  1973.0  1973.0
1974   3.0  1974.0  0.0  1974.0  1974.0  1974.0  1974.0  1974.0
1975   4.0  1975.0  0.0  1975.0  1975.0  1975.0  1975.0  1975.0
1976   4.0  1976.0  0.0  1976.0  1976.0  1976.0  1976.0  1976.0
1977   3.0  1977.0  0.0  1977.0  1977.0  1977.0  1977.0  1977.0
1978   3.0  1978.0  0.0  1978.0  1978.0  1978.0  1978.0  1978.0
1979   4.0  1979.0  0.0  1979.0  1979.0  1979.0  1979.0  1979.0
1980   6.0  1980.0  0.0  1980.0  1980.0  1980.0  1980.0  1980.0
1981   5.0  1981.0  0.0  1981.0  1981.0  1981.0  1981.0  1981.0
1982   5.0  1982.0  0.0  1982.0  1982.0  1982.0  1982.0  1982.0
1983   5.0  1983.0  0.0  1983.0  1983.0  1983.0  1983.0  1983.0
1984   5.0  1984.0  0.0  1984.0  1984.0  1984.0  1984.0  1984.0
1985   6.0  1985.0  0.0  1985.0  1985.0  1985.0  1985.0  1985.0
1986   5.0  1986.0  0.0  1986.0  1986.0  1986.0  1986.0  1986.0
1987   5.0  1987.0  0.0  1987.0  1987.0  1987.0  1987.0  1987.0
1988   5.0  1988.0  0.0  1988.0  1988.0  1988.0  1988.0  1988.0
1989   5.0  1989.0  0.0  1989.0  1989.0  1989.0  1989.0  1989.0
1990   6.0  1990.0  0.0  1990.0  1990.0  1990.0  1990.0  1990.0
1991   5.0  1991.0  0.0  1991.0  1991.0  1991.0  1991.0  1991.0
1992   6.0  1992.0  0.0  1992.0  1992.0  1992.0  1992.0  1992.0
1993   6.0  1993.0  0.0  1993.0  1993.0  1993.0  1993.0  1993.0
1994   6.0  1994.0  0.0  1994.0  1994.0  1994.0  1994.0  1994.0
1995   6.0  1995.0  0.0  1995.0  1995.0  1995.0  1995.0  1995.0
1996   6.0  1996.0  0.0  1996.0  1996.0  1996.0  1996.0  1996.0
1997   6.0  1997.0  0.0  1997.0  1997.0  1997.0  1997.0  1997.0
1998   6.0  1998.0  0.0  1998.0  1998.0  1998.0  1998.0  1998.0
1999   6.0  1999.0  0.0  1999.0  1999.0  1999.0  1999.0  1999.0
2000   6.0  2000.0  0.0  2000.0  2000.0  2000.0  2000.0  2000.0
2001   6.0  2001.0  0.0  2001.0  2001.0  2001.0  2001.0  2001.0
2002   6.0  2002.0  0.0  2002.0  2002.0  2002.0  2002.0  2002.0
2003   6.0  2003.0  0.0  2003.0  2003.0  2003.0  2003.0  2003.0
2004   6.0  2004.0  0.0  2004.0  2004.0  2004.0  2004.0  2004.0
2005   6.0  2005.0  0.0  2005.0  2005.0  2005.0  2005.0  2005.0
2006   6.0  2006.0  0.0  2006.0  2006.0  2006.0  2006.0  2006.0
2007   6.0  2007.0  0.0  2007.0  2007.0  2007.0  2007.0  2007.0
2008   6.0  2008.0  0.0  2008.0  2008.0  2008.0  2008.0  2008.0
2009   6.0  2009.0  0.0  2009.0  2009.0  2009.0  2009.0  2009.0
2010   6.0  2010.0  0.0  2010.0  2010.0  2010.0  2010.0  2010.0
2011   6.0  2011.0  0.0  2011.0  2011.0  2011.0  2011.0  2011.0
2012   6.0  2012.0  0.0  2012.0  2012.0  2012.0  2012.0  2012.0
2013   6.0  2013.0  0.0  2013.0  2013.0  2013.0  2013.0  2013.0
2014   6.0  2014.0  0.0  2014.0  2014.0  2014.0  2014.0  2014.0
2015   6.0  2015.0  0.0  2015.0  2015.0  2015.0  2015.0  2015.0
2016   6.0  2016.0  0.0  2016.0  2016.0  2016.0  2016.0  2016.0
2017   6.0  2017.0  0.0  2017.0  2017.0  2017.0  2017.0  2017.0
2018   6.0  2018.0  0.0  2018.0  2018.0  2018.0  2018.0  2018.0
2019   6.0  2019.0  0.0  2019.0  2019.0  2019.0  2019.0  2019.0
2020   6.0  2020.0  0.0  2020.0  2020.0  2020.0  2020.0  2020.0

     Life_Expectancy
               count       mean       std   min     25%    50%     75%   max
Year
1970             5.0  71.520000  0.719027  70.6  70.900  71.90  72.000  72.2
1971             5.0  71.920000  0.936483  70.8  71.200  71.90  72.800  72.9
1972             3.0  71.800000  1.216553  71.0  71.100  71.20  72.200  73.2
1973             3.0  72.033333  1.184624  71.3  71.350  71.40  72.400  73.4
1974             3.0  72.400000  1.153256  71.5  71.750  72.00  72.850  73.7
1975             4.0  72.850000  1.190238  71.4  72.375  72.85  73.325  74.3
1976             4.0  73.325000  1.278997  71.8  72.625  73.35  74.050  74.8
1977             3.0  73.700000  1.442221  72.5  72.900  73.30  74.300  75.3
1978             3.0  73.866667  1.680278  72.4  72.950  73.50  74.600  75.7
1979             4.0  74.500000  1.471960  72.8  73.625  74.50  75.375  76.2
1980             6.0  74.233333  1.229092  72.9  73.325  74.00  74.975  76.1
1981             5.0  74.620000  1.347961  73.2  73.800  74.10  75.500  76.5
1982             5.0  74.920000  1.346105  73.5  74.100  74.50  75.600  76.9
1983             5.0  75.120000  1.306522  73.8  74.300  74.60  75.900  77.0
1984             5.0  75.420000  1.336787  74.3  74.500  74.70  76.200  77.4
1985             6.0  75.616667  1.140906  74.7  74.775  75.20  76.075  77.6
1986             5.0  75.860000  1.443260  74.7  74.800  75.20  76.500  78.1
1987             5.0  76.180000  1.465264  74.9  75.200  75.60  76.700  78.5
1988             5.0  76.260000  1.393915  74.9  75.300  75.90  76.800  78.4
1989             5.0  76.480000  1.505656  75.1  75.400  76.00  77.100  78.8
1990             6.0  76.916667  1.290607  75.3  76.025  77.15  77.300  78.9
1991             5.0  77.060000  1.436315  75.5  75.900  77.20  77.600  79.1
1992             6.0  77.100000  1.316055  75.7  76.150  76.90  77.725  79.2
1993             6.0  77.083333  1.435851  75.5  76.125  76.85  77.725  79.4
1994             6.0  77.450000  1.443260  75.7  76.575  77.35  77.975  79.8
1995             6.0  77.450000  1.392480  75.7  76.625  77.35  78.075  79.6
1996             6.0  77.766667  1.488176  76.1  76.900  77.55  78.200  80.3
1997             6.0  78.066667  1.417980  76.5  77.225  77.80  78.525  80.5
1998             6.0  78.283333  1.381907  76.7  77.400  78.15  78.750  80.6
1999             6.0  78.383333  1.324261  76.7  77.600  78.35  78.875  80.5
2000             6.0  78.716667  1.519759  76.7  77.975  78.65  79.175  81.2
2001             6.0  78.950000  1.530686  76.9  78.275  78.90  79.300  81.5
2002             6.0  79.083333  1.609244  77.0  78.350  78.95  79.475  81.8
2003             6.0  79.133333  1.569289  77.1  78.450  78.95  79.525  81.8
2004             6.0  79.683333  1.503884  77.6  79.050  79.55  80.200  82.1
2005             6.0  79.766667  1.455564  77.6  79.250  79.70  80.300  82.0
2006             6.0  80.150000  1.543697  77.8  79.575  80.10  80.850  82.4
2007             6.0  80.366667  1.506873  78.1  79.800  80.30  81.025  82.6
2008             6.0  80.483333  1.551021  78.1  79.900  80.45  81.225  82.7
2009             6.0  80.766667  1.485485  78.5  80.325  80.65  81.350  83.0
2010             6.0  80.933333  1.444530  78.6  80.525  80.90  81.650  82.9
2011             6.0  81.100000  1.429685  78.7  80.625  81.20  82.075  82.7
2012             6.0  81.216667  1.491867  78.8  80.700  81.30  81.975  83.2
2013             6.0  81.316667  1.571517  78.8  80.725  81.40  82.150  83.4
2014             6.0  81.633333  1.635441  78.9  81.250  81.60  82.550  83.7
2015             6.0  81.433333  1.756891  78.7  80.775  81.45  82.275  83.9
2016             6.0  81.616667  1.819249  78.7  81.050  81.60  82.525  84.1
2017             6.0  81.633333  1.865118  78.6  81.150  81.60  82.500  84.2
2018             6.0  81.683333  1.881932  78.7  81.075  81.65  82.600  84.3
2019             6.0  81.833333  1.872610  78.8  81.325  81.80  82.725  84.4
2020             6.0  81.200000  2.529822  77.0  80.575  81.40  82.150  84.7

###country wise life expetency trend

In [32]:

df.groupby("Country")[['Year','Life_Expectancy']].mean()

                      Year  Life_Expectancy
Country
Canada         1998.318182        78.706818
France         2001.857143        79.565714
Germany        1995.080000        76.726000
Great Britain  1998.627907        77.620930
Japan          1995.000000        79.554902
USA            1995.000000        75.843137

In [34]:
df.groupby("Country")[['Life_Expectancy']].describe()

              Life_Expectancy                                           \
                        count       mean       std   min     25%   50%
Country
Canada                   44.0  78.706818  2.502222  72.8  76.775  78.7
France                   35.0  79.565714  2.862120  72.2  78.050  79.4
Germany                  50.0  76.726000  3.473915  70.6  73.575  77.1
Great Britain            43.0  77.620930  2.827548  71.9  75.350  77.5
Japan                    51.0  79.554902  3.547242  72.0  76.950  79.8
USA                      51.0  75.843137  2.336258  70.9  74.550  75.7


                  75%   max
Country
Canada         80.975  82.2
France         82.200  82.9
Germany        80.175  81.3
Great Britain  80.400  81.4
Japan          82.650  84.7
USA            77.950  78.9